### ISSUE TITLE
test_auto3dseg_ensemble

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/research-contributions#186]
**Describe the bug**
with the latest monai core in the folder `MONAI`:
```
cp -r research-contributions/auto3dseg/algorithm_templates ../MONAI/
MONAI_TESTING_ALGO_TEMPLATE=algorithm_templates  python -m tests.test_auto3dseg_ensemble
```

error:
```
[2023-02-15T08:00:15.292Z] + python -m tests.test_auto3dseg_ensemble
[2023-02-15T08:00:23.403Z] monai.transforms.io.dictionary LoadImaged.__init__:image_only: Current default value of argument `image_only=False` has been deprecated since version 1.1. It will be changed to `image_only=True` in version 1.3.
[2023-02-15T08:00:23.662Z] 
  0%|          | 0/12 [00:00<?, ?it/s]
  8%|▊         | 1/12 [00:00<00:01,  7.90it/s]
 67%|██████▋   | 8/12 [00:00<00:00, 37.88it/s]
100%|██████████| 12/12 [00:00<00:00, 36.58it/s]2023-02-15 08:00:23,509 - INFO - BundleGen from directory algorithm_templates
[2023-02-15T08:00:23.664Z] 2023-02-15 08:00:23,515 - INFO - segresnet -- {'_target_': 'segresnet.scripts.algo.SegresnetAlgo', 'template_path': '/tmp/tmpp5__p2gw/workdir/algorithm_templates/segresnet'}
[2023-02-15T08:00:23.664Z] 2023-02-15 08:00:23,515 - INFO - swinunetr -- {'_target_': 'swinunetr.scripts.algo.SwinunetrAlgo', 'template_path': '/tmp/tmpp5__p2gw/workdir/algorithm_templates/swinunetr'}
[2023-02-15T08:00:23.664Z] 2023-02-15 08:00:23,515 - INFO - dints -- {'_target_': 'dints.scripts.algo.DintsAlgo', 'template_path': '/tmp/tmpp5__p2gw/workdir/algorithm_templates/dints'}
[2023-02-15T08:00:23.664Z] 2023-02-15 08:00:23,515 - INFO - segresnet2d -- {'_target_': 'segresnet2d.scripts.algo.Segresnet2dAlgo', 'template_path': '/tmp/tmpp5__p2gw/workdir/algorithm_templates/segresnet2d'}
[2023-02-15T08:00:24.227Z] Loaded self.data_list_file /tmp/tmpp5__p2gw/workdir/data_src_cfg.yaml
[2023-02-15T08:00:24.229Z] 2023-02-15 08:00:23,942 - INFO - /tmp/tmpp5__p2gw/workdir/segresnet_0
[2023-02-15T08:00:24.229Z] 2023-02-15 08:00:24,135 - INFO - /tmp/tmpp5__p2gw/workdir/swinunetr_0
[2023-02-15T08:00:24.485Z] 2023-02-15 08:00:24,337 - INFO - /tmp/tmpp5__p2gw/workdir/dints_0
[2023-02-15T08:00:24.744Z] 2023-02-15 08:00:24,517 - INFO - /tmp/tmpp5__p2gw/workdir/segresnet2d_0
[2023-02-15T08:00:24.745Z] 2023-02-15 08:00:24,530 - INFO - Launching: python /tmp/tmpp5__p2gw/workdir/segresnet_0/scripts/train.py run --config_file='/tmp/tmpp5__p2gw/workdir/segresnet_0/configs/hyper_parameters.yaml' --num_images_per_batch=2 --num_epochs=2 --num_epochs_per_validation=1 --num_warmup_epochs=1 --use_pretrain=False --pretrained_path= --determ=True --network#init_filters=8 --pretrained_ckpt_name=
[2023-02-15T08:00:31.295Z] Segmenter 0 /tmp/tmpp5__p2gw/workdir/segresnet_0/configs/hyper_parameters.yaml {'num_images_per_batch': 2, 'num_epochs': 2, 'num_epochs_per_validation': 1, 'num_warmup_epochs': 1, 'use_pretrain': False, 'pretrained_path': '', 'determ': True, 'network#init_filters': 8, 'pretrained_ckpt_name': ''}
[2023-02-15T08:00:31.295Z] _meta_: {}
[2023-02-15T08:00:31.295Z] acc: null
[2023-02-15T08:00:31.295Z] amp: true
[2023-02-15T08:00:31.295Z] batch_size: 2
[2023-02-15T08:00:31.295Z] bundle_root: /tmp/tmpp5__p2gw/workdir/segresnet_0
[2023-02-15T08:00:31.295Z] cache_rate: null
[2023-02-15T08:00:31.295Z] ckpt_path: /tmp/tmpp5__p2gw/workdir/segresnet_0/model
[2023-02-15T08:00:31.295Z] ckpt_save: true
[2023-02-15T08:00:31.295Z] class_index: null
[2023-02-15T08:00:31.295Z] class_names:
[2023-02-15T08:00:31.295Z] - label_class
[2023-02-15T08:00:31.295Z] crop_mode: rand
[2023-02-15T08:00:31.295Z] crop_ratios: null
[2023-02-15T08:00:31.295Z] cuda: true
[2023-02-15T08:00:31.295Z] data_file_base_dir: /tmp/tmpp5__p2gw/dataroot
[2023-02-15T08:00:31.295Z] data_list_file_path: /tmp/tmpp5__p2gw/dataroot/fake_input.json
[2023-02-15T08:00:31.295Z] determ: true
[2023-02-15T08:00:31.295Z] extra_modalities: {}
[2023-02-15T08:00:31.295Z] finetune:
[2023-02-15T08:00:31.295Z]   ckpt_name: /tmp/tmpp5__p2gw/workdir/segresnet_0/model/model.pt
[2023-02-15T08:00:31.295Z]   enabled: false
[2023-02-15T08:00:31.295Z] fold: 0
[2023-02-15T08:00:31.295Z] image_size:
[2023-02-15T08:00:31.295Z] - 24
[2023-02-15T08:00:31.295Z] - 24
[2023-02-15T08:00:31.295Z] - 24
[2023-02-15T08:00:31.295Z] infer:
[2023-02-15T08:00:31.295Z]   ckpt_name: /tmp/tmpp5__p2gw/workdir/segresnet_0/model/model.pt
[2023-02-15T08:00:31.295Z]   data_list_key: testing
[2023-02-15T08:00:31.295Z]   enabled: false
[2023-02-15T08:00:31.295Z]   output_path: /tmp/tmpp5__p2gw/workdir/segresnet_0/prediction_testing
[2023-02-15T08:00:31.295Z] input_channels: 1
[2023-02-15T08:00:31.295Z] intensity_bounds:
[2023-02-15T08:00:31.295Z] - 0.6218280543883642
[2023-02-15T08:00:31.295Z] - 1.0
[2023-02-15T08:00:31.295Z] learning_rate: 0.0002
[2023-02-15T08:00:31.295Z] loss:
[2023-02-15T08:00:31.295Z]   _target_: DiceCELoss
[2023-02-15T08:00:31.295Z]   include_background: true
[2023-02-15T08:00:31.295Z]   sigmoid: $@sigmoid
[2023-02-15T08:00:31.295Z]   smooth_dr: 1.0e-05
[2023-02-15T08:00:31.295Z]   smooth_nr: 0
[2023-02-15T08:00:31.295Z]   softmax: $not @sigmoid
[2023-02-15T08:00:31.295Z]   squared_pred: true
[2023-02-15T08:00:31.295Z]   to_onehot_y: $not @sigmoid
[2023-02-15T08:00:31.295Z] modality: mri
[2023-02-15T08:00:31.295Z] multigpu: false
[2023-02-15T08:00:31.295Z] name: fake_data
[2023-02-15T08:00:31.295Z] network:
[2023-02-15T08:00:31.295Z]   _target_: SegResNetDS
[2023-02-15T08:00:31.295Z]   blocks_down:
[2023-02-15T08:00:31.295Z]   - 1
[2023-02-15T08:00:31.295Z]   - 2
[2023-02-15T08:00:31.295Z]   - 2
[2023-02-15T08:00:31.295Z]   - 4
[2023-02-15T08:00:31.295Z]   - 4
[2023-02-15T08:00:31.295Z]   dsdepth: 4
[2023-02-15T08:00:31.295Z]   in_channels: '@input_channels'
[2023-02-15T08:00:31.295Z]   init_filters: 8
[2023-02-15T08:00:31.295Z]   norm: BATCH
[2023-02-15T08:00:31.295Z]   out_channels: '@output_classes'
[2023-02-15T08:00:31.295Z] normalize_mode: meanstd
[2023-02-15T08:00:31.295Z] num_epochs: 2
[2023-02-15T08:00:31.295Z] num_epochs_per_saving: 1
[2023-02-15T08:00:31.295Z] num_epochs_per_validation: 1
[2023-02-15T08:00:31.295Z] num_images_per_batch: 2
[2023-02-15T08:00:31.295Z] num_warmup_epochs: 1
[2023-02-15T08:00:31.295Z] num_workers: 4
[2023-02-15T08:00:31.295Z] optimizer:
[2023-02-15T08:00:31.295Z]   _target_: torch.optim.AdamW
[2023-02-15T08:00:31.295Z]   lr: '@learning_rate'
[2023-02-15T08:00:31.295Z]   weight_decay: 1.0e-05
[2023-02-15T08:00:31.295Z] output_classes: 2
[2023-02-15T08:00:31.295Z] pretrained_ckpt_name: null
[2023-02-15T08:00:31.295Z] pretrained_path: ''
[2023-02-15T08:00:31.295Z] quick: false
[2023-02-15T08:00:31.295Z] rank: 0
[2023-02-15T08:00:31.295Z] resample: false
[2023-02-15T08:00:31.295Z] resample_resolution:
[2023-02-15T08:00:31.295Z] - 1.0
[2023-02-15T08:00:31.295Z] - 1.0
[2023-02-15T08:00:31.295Z] - 1.0
[2023-02-15T08:00:31.295Z] roi_size:
[2023-02-15T08:00:31.295Z] - 32
[2023-02-15T08:00:31.295Z] - 32
[2023-02-15T08:00:31.295Z] - 32
[2023-02-15T08:00:31.295Z] sigmoid: false
[2023-02-15T08:00:31.295Z] spacing_lower:
[2023-02-15T08:00:31.295Z] - 1.0
[2023-02-15T08:00:31.295Z] - 1.0
[2023-02-15T08:00:31.295Z] - 1.0
[2023-02-15T08:00:31.295Z] spacing_upper:
[2023-02-15T08:00:31.295Z] - 1.0
[2023-02-15T08:00:31.295Z] - 1.0
[2023-02-15T08:00:31.295Z] - 1.0
[2023-02-15T08:00:31.295Z] task: segmentation
[2023-02-15T08:00:31.295Z] use_pretrain: false
[2023-02-15T08:00:31.295Z] validate:
[2023-02-15T08:00:31.295Z]   ckpt_name: /tmp/tmpp5__p2gw/workdir/segresnet_0/model/model.pt
[2023-02-15T08:00:31.295Z]   enabled: false
[2023-02-15T08:00:31.295Z]   invert: true
[2023-02-15T08:00:31.295Z]   output_path: /tmp/tmpp5__p2gw/workdir/segresnet_0/prediction_validation
[2023-02-15T08:00:31.295Z]   save_mask: false
[2023-02-15T08:00:31.295Z] warmup_epochs: 13
[2023-02-15T08:00:31.295Z] 
[2023-02-15T08:00:31.295Z] Total parameters count 5451088 distributed False
[2023-02-15T08:00:31.295Z] Segmenter train called
[2023-02-15T08:00:31.295Z] train_files files 8 validation files 4
[2023-02-15T08:00:31.295Z] Calculating cache required 0GB, available RAM 59GB given avg image size [24, 24, 24].
[2023-02-15T08:00:31.295Z] Caching full dataset in RAM
[2023-02-15T08:00:31.295Z] monai.transforms.io.dictionary LoadImaged.__init__:image_only: Current default value of argument `image_only=False` has been deprecated since version 1.1. It will be changed to `image_only=True` in version 1.3.
[2023-02-15T08:00:31.295Z] Writing Tensorboard logs to  /tmp/tmpp5__p2gw/workdir/segresnet_0/model
[2023-02-15T08:00:32.664Z] Epoch 0/2 0/4 loss: 2.2924 acc [ 0.317] time 1.34s
[2023-02-15T08:00:32.664Z] Epoch 0/2 1/4 loss: 2.2695 acc [ 0.333] time 0.05s
[2023-02-15T08:00:32.664Z] Epoch 0/2 2/4 loss: 2.2174 acc [ 0.430] time 0.04s
[2023-02-15T08:00:32.664Z] Epoch 0/2 3/4 loss: 2.1881 acc [ 0.453] time 0.04s
[2023-02-15T08:00:32.664Z] Final training  0/1 loss: 2.1881 acc_avg: 0.4532 acc [ 0.453] time 1.47s
[2023-02-15T08:00:34.558Z] Val 0/2 0/4 loss: 1.0084 acc [ 0.159] time 0.59s
[2023-02-15T08:00:34.558Z] Val 0/2 1/4 loss: 1.0317 acc [ 0.171] time 0.01s
[2023-02-15T08:00:34.558Z] Val 0/2 2/4 loss: 1.0241 acc [ 0.206] time 0.01s
[2023-02-15T08:00:34.558Z] Val 0/2 3/4 loss: 1.0204 acc [ 0.218] time 0.01s
[2023-02-15T08:00:34.558Z] Final validation  0/1 loss: 1.0204 acc_avg: 0.2178 acc [ 0.218] time 0.61s
[2023-02-15T08:00:34.558Z] New best metric (-1.000000 --> 0.217803). 
[2023-02-15T08:00:34.558Z] Saving checkpoint process: /tmp/tmpp5__p2gw/workdir/segresnet_0/model/model.pt {'epoch': 0, 'best_metric': 0.2178034782409668} save_time 0.04s
[2023-02-15T08:00:34.558Z] Progress:  best_avg_dice_score_epoch: 0, best_avg_dice_score: 0.2178034782409668, save_time: 0.04168510437011719, train_time: 1.47s, validation_time: 0.61s, epoch_time: 2.09s, model: /tmp/tmpp5__p2gw/workdir/segresnet_0/model/model.pt, date: 2023-02-15 08:00:33
[2023-02-15T08:00:34.558Z] Epoch 1/2 0/4 loss: 2.0491 acc [ 0.579] time 0.37s
[2023-02-15T08:00:34.558Z] Epoch 1/2 1/4 loss: 1.9655 acc [ 0.537] time 0.05s
[2023-02-15T08:00:34.558Z] Epoch 1/2 2/4 loss: 1.9070 acc [ 0.522] time 0.05s
[2023-02-15T08:00:34.558Z] Epoch 1/2 3/4 loss: 1.8529 acc [ 0.546] time 0.05s
[2023-02-15T08:00:34.558Z] Final training  1/1 loss: 1.8529 acc_avg: 0.5462 acc [ 0.546] time 0.51s
[2023-02-15T08:00:34.558Z] Val 1/2 0/4 loss: 0.9930 acc [ 0.218] time 0.14s
[2023-02-15T08:00:34.558Z] Val 1/2 1/4 loss: 1.0140 acc [ 0.229] time 0.13s
[2023-02-15T08:00:34.558Z] Val 1/2 2/4 loss: 1.0056 acc [ 0.258] time 0.06s
[2023-02-15T08:00:34.558Z] Val 1/2 3/4 loss: 1.0033 acc [ 0.264] time 0.01s
[2023-02-15T08:00:34.558Z] Final validation  1/1 loss: 1.0033 acc_avg: 0.2635 acc [ 0.264] time 0.34s
[2023-02-15T08:00:34.558Z] New best metric (0.217803 --> 0.263549). 
[2023-02-15T08:00:34.558Z] Saving checkpoint process: /tmp/tmpp5__p2gw/workdir/segresnet_0/model/model.pt {'epoch': 1, 'best_metric': 0.263549268245697} save_time 0.09s
[2023-02-15T08:00:34.558Z] Progress:  best_avg_dice_score_epoch: 1, best_avg_dice_score: 0.263549268245697, save_time: 0.0931248664855957, train_time: 0.51s, validation_time: 0.34s, epoch_time: 0.86s, model: /tmp/tmpp5__p2gw/workdir/segresnet_0/model/model.pt, date: 2023-02-15 08:00:34
[2023-02-15T08:00:34.558Z] train completed, best_metric: 0.2635 at epoch: 1
[2023-02-15T08:00:35.496Z] 2023-02-15 08:00:35,388 - INFO - Launching: python /tmp/tmpp5__p2gw/workdir/swinunetr_0/scripts/train.py run --config_file='/tmp/tmpp5__p2gw/workdir/swinunetr_0/configs/transforms_validate.yaml','/tmp/tmpp5__p2gw/workdir/swinunetr_0/configs/transforms_train.yaml','/tmp/tmpp5__p2gw/workdir/swinunetr_0/configs/network.yaml','/tmp/tmpp5__p2gw/workdir/swinunetr_0/configs/hyper_parameters.yaml','/tmp/tmpp5__p2gw/workdir/swinunetr_0/configs/transforms_infer.yaml' --num_images_per_batch=2 --num_epochs=2 --num_epochs_per_validation=1 --num_warmup_epochs=1 --use_pretrain=False --pretrained_path= --determ=True --network#feature_size=12
[2023-02-15T08:00:43.589Z] [info] number of GPUs: 1
[2023-02-15T08:00:43.589Z] [info] world_size: 1
[2023-02-15T08:00:43.589Z] train_files: 8
[2023-02-15T08:00:43.589Z] val_files: 4
[2023-02-15T08:00:43.589Z] num_epochs 2
[2023-02-15T08:00:43.589Z] num_epochs_per_validation 1
[2023-02-15T08:00:43.589Z] [info] training from scratch
[2023-02-15T08:00:43.589Z] [info] amp enabled
[2023-02-15T08:00:43.589Z] ----------
[2023-02-15T08:00:43.589Z] epoch 1/2
[2023-02-15T08:00:43.589Z] learning rate is set to 0.0001
[2023-02-15T08:00:43.589Z] monai.transforms.io.dictionary LoadImaged.__init__:image_only: Current default value of argument `image_only=False` has been deprecated since version 1.1. It will be changed to `image_only=True` in version 1.3.
[2023-02-15T08:00:44.519Z] [2023-02-15 08:00:43] 1/4, train_loss: 1.3057
[2023-02-15T08:00:44.519Z] [2023-02-15 08:00:43] 2/4, train_loss: 1.2854
[2023-02-15T08:00:44.519Z] [2023-02-15 08:00:44] 3/4, train_loss: 1.2569
[2023-02-15T08:00:44.519Z] [2023-02-15 08:00:44] 4/4, train_loss: 1.2262
[2023-02-15T08:00:44.519Z] epoch 1 average loss: 1.2685, best mean dice: -1.0000 at epoch -1
[2023-02-15T08:00:45.448Z] 1 / 4 tensor([[0.5952]], device='cuda:0')
[2023-02-15T08:00:45.448Z] 2 / 4 tensor([[0.6565]], device='cuda:0')
[2023-02-15T08:00:45.448Z] 3 / 4 tensor([[0.5871]], device='cuda:0')
[2023-02-15T08:00:45.448Z] 4 / 4 tensor([[0.6294]], device='cuda:0')
[2023-02-15T08:00:45.448Z] evaluation metric - class 1: 0.6170290112495422
[2023-02-15T08:00:45.448Z] avg_metric 0.6170290112495422
[2023-02-15T08:00:45.448Z] saved new best metric model
[2023-02-15T08:00:45.448Z] current epoch: 1 current mean dice: 0.6170 best mean dice: 0.6170 at epoch 1
[2023-02-15T08:00:45.448Z] ----------
[2023-02-15T08:00:45.448Z] epoch 2/2
[2023-02-15T08:00:45.448Z] learning rate is set to 5e-05
[2023-02-15T08:00:46.814Z] [2023-02-15 08:00:45] 1/4, train_loss: 1.2206
[2023-02-15T08:00:46.814Z] [2023-02-15 08:00:46] 2/4, train_loss: 1.2036
[2023-02-15T08:00:46.814Z] [2023-02-15 08:00:46] 3/4, train_loss: 1.2080
[2023-02-15T08:00:46.814Z] [2023-02-15 08:00:46] 4/4, train_loss: 1.1929
[2023-02-15T08:00:46.814Z] epoch 2 average loss: 1.2063, best mean dice: 0.6170 at epoch 1
[2023-02-15T08:00:47.378Z] 1 / 4 tensor([[0.5828]], device='cuda:0')
[2023-02-15T08:00:47.378Z] 2 / 4 tensor([[0.6483]], device='cuda:0')
[2023-02-15T08:00:47.378Z] 3 / 4 tensor([[0.5890]], device='cuda:0')
[2023-02-15T08:00:47.378Z] 4 / 4 tensor([[0.6318]], device='cuda:0')
[2023-02-15T08:00:47.378Z] evaluation metric - class 1: 0.6129776835441589
[2023-02-15T08:00:47.378Z] avg_metric 0.6129776835441589
[2023-02-15T08:00:47.378Z] current epoch: 2 current mean dice: 0.6130 best mean dice: 0.6170 at epoch 1
[2023-02-15T08:00:47.378Z] train completed, best_metric: 0.6170 at epoch: 1
[2023-02-15T08:00:47.378Z] 0.6170290112495422
[2023-02-15T08:00:48.309Z] 2023-02-15 08:00:48,277 - INFO - The keys use_pretrain cannot be found in the /tmp/tmpp5__p2gw/workdir/dints_0/configs/hyper_parameters_search.yaml for architecture search. Skipped overriding key use_pretrain.
[2023-02-15T08:00:48.309Z] 2023-02-15 08:00:48,277 - INFO - The keys pretrained_path cannot be found in the /tmp/tmpp5__p2gw/workdir/dints_0/configs/hyper_parameters_search.yaml for architecture search. Skipped overriding key pretrained_path.
[2023-02-15T08:00:48.310Z] 2023-02-15 08:00:48,278 - INFO - Launching: python /tmp/tmpp5__p2gw/workdir/dints_0/scripts/search.py run --config_file='/tmp/tmpp5__p2gw/workdir/dints_0/configs/transforms_validate.yaml','/tmp/tmpp5__p2gw/workdir/dints_0/configs/transforms_train.yaml','/tmp/tmpp5__p2gw/workdir/dints_0/configs/network.yaml','/tmp/tmpp5__p2gw/workdir/dints_0/configs/hyper_parameters.yaml','/tmp/tmpp5__p2gw/workdir/dints_0/configs/transforms_infer.yaml','/tmp/tmpp5__p2gw/workdir/dints_0/configs/hyper_parameters_search.yaml','/tmp/tmpp5__p2gw/workdir/dints_0/configs/network_search.yaml' --searching#num_images_per_batch=2 --searching#num_epochs=2 --searching#num_epochs_per_validation=1 --searching#num_warmup_epochs=1 --searching#determ=True
[2023-02-15T08:00:58.265Z] [info] number of GPUs: 1
[2023-02-15T08:00:58.265Z] [info] world_size: 1
[2023-02-15T08:00:58.265Z] train_files_w: 4
[2023-02-15T08:00:58.265Z] train_files_a: 4
[2023-02-15T08:00:58.265Z] val_files: 4
[2023-02-15T08:00:58.265Z] 2023-02-15 08:00:54.781294 - Length of input patch is recommended to be a multiple of 32.
[2023-02-15T08:00:58.265Z] num_epochs 2
[2023-02-15T08:00:58.265Z] num_epochs_warmup 1
[2023-02-15T08:00:58.265Z] num_epochs_per_validation 1
[2023-02-15T08:00:58.265Z] [info] amp enabled
[2023-02-15T08:00:58.265Z] ----------
[2023-02-15T08:00:58.265Z] epoch 1/2
[2023-02-15T08:00:58.265Z] learning rate is set to 0.025
[2023-02-15T08:00:58.265Z] monai.transforms.io.dictionary LoadImaged.__init__:image_only: Current default value of argument `image_only=False` has been deprecated since version 1.1. It will be changed to `image_only=True` in version 1.3.
[2023-02-15T08:01:20.164Z] [2023-02-15 08:01:00] 1/2, train_loss: 0.7309
[2023-02-15T08:01:20.166Z] [2023-02-15 08:01:01] 2/2, train_loss: 0.6869
[2023-02-15T08:01:20.168Z] epoch 1 average loss: 0.7089, best mean dice: -1.0000 at epoch -1
[2023-02-15T08:01:20.168Z] 1 / 4 tensor([[0.5261]], device='cuda:0')
[2023-02-15T08:01:20.168Z] 2 / 4 tensor([[0.4058]], device='cuda:0')
[2023-02-15T08:01:20.168Z] 3 / 4 tensor([[0.3060]], device='cuda:0')
[2023-02-15T08:01:20.168Z] 4 / 4 tensor([[0.3371]], device='cuda:0')
[2023-02-15T08:01:20.168Z] evaluation metric - class 1: 0.39373794198036194
[2023-02-15T08:01:20.168Z] avg_metric 0.39373794198036194
[2023-02-15T08:01:20.168Z] saved new best metric model
[2023-02-15T08:01:20.168Z] current epoch: 1 current mean dice: 0.3937 best mean dice: 0.3937 at epoch 1
[2023-02-15T08:01:20.168Z] ----------
[2023-02-15T08:01:20.168Z] epoch 2/2
[2023-02-15T08:01:20.168Z] learning rate is set to 0.0125
[2023-02-15T08:01:20.423Z] [2023-02-15 08:01:20] 1/2, train_loss: 0.6936
[2023-02-15T08:01:42.332Z] [2023-02-15 08:01:22] 1/2, train_loss_arch: 0.6852
[2023-02-15T08:01:42.332Z] [2023-02-15 08:01:23] 2/2, train_loss: 0.6829
[2023-02-15T08:01:42.332Z] [2023-02-15 08:01:24] 2/2, train_loss_arch: 0.6855
[2023-02-15T08:01:42.332Z] epoch 2 average loss: 0.6882, best mean dice: 0.3937 at epoch 1
[2023-02-15T08:01:42.332Z] epoch 2 average arch loss: 0.6853, best mean dice: 0.3937 at epoch 1
[2023-02-15T08:01:42.332Z] 1 / 4 tensor([[0.5331]], device='cuda:0')
[2023-02-15T08:01:42.332Z] 2 / 4 tensor([[0.5480]], device='cuda:0')
[2023-02-15T08:01:42.332Z] 3 / 4 tensor([[0.2535]], device='cuda:0')
[2023-02-15T08:01:42.332Z] 4 / 4 tensor([[0.3969]], device='cuda:0')
[2023-02-15T08:01:42.332Z] evaluation metric - class 1: 0.43287837505340576
[2023-02-15T08:01:42.332Z] avg_metric 0.43287837505340576
[2023-02-15T08:01:42.332Z] saved new best metric model
[2023-02-15T08:01:42.332Z] current epoch: 2 current mean dice: 0.4329 best mean dice: 0.4329 at epoch 2
[2023-02-15T08:01:42.332Z] train completed, best_metric: 0.4329 at epoch: 2
[2023-02-15T08:01:42.332Z] 2023-02-15 08:01:40,568 - INFO - The keys num_warmup_epochs cannot be found in the /tmp/tmpp5__p2gw/workdir/dints_0/configs/hyper_parameters.yaml for training. Skipped overriding key num_warmup_epochs.
[2023-02-15T08:01:42.332Z] 2023-02-15 08:01:40,569 - INFO - The keys use_pretrain cannot be found in the /tmp/tmpp5__p2gw/workdir/dints_0/configs/hyper_parameters.yaml for training. Skipped overriding key use_pretrain.
[2023-02-15T08:01:42.332Z] 2023-02-15 08:01:40,569 - INFO - The keys pretrained_path cannot be found in the /tmp/tmpp5__p2gw/workdir/dints_0/configs/hyper_parameters.yaml for training. Skipped overriding key pretrained_path.
[2023-02-15T08:01:42.332Z] 2023-02-15 08:01:40,569 - INFO - Launching: python /tmp/tmpp5__p2gw/workdir/dints_0/scripts/train.py run --config_file='/tmp/tmpp5__p2gw/workdir/dints_0/configs/transforms_validate.yaml','/tmp/tmpp5__p2gw/workdir/dints_0/configs/transforms_train.yaml','/tmp/tmpp5__p2gw/workdir/dints_0/configs/network.yaml','/tmp/tmpp5__p2gw/workdir/dints_0/configs/hyper_parameters.yaml','/tmp/tmpp5__p2gw/workdir/dints_0/configs/transforms_infer.yaml','/tmp/tmpp5__p2gw/workdir/dints_0/configs/hyper_parameters_search.yaml','/tmp/tmpp5__p2gw/workdir/dints_0/configs/network_search.yaml' --training#num_images_per_batch=2 --training#num_epochs=2 --training#num_epochs_per_validation=1 --training#determ=True
[2023-02-15T08:01:50.426Z] [info] number of GPUs: 1
[2023-02-15T08:01:50.426Z] [info] world_size: 1
[2023-02-15T08:01:50.426Z] train_files: 8
[2023-02-15T08:01:50.426Z] val_files: 4
[2023-02-15T08:01:50.426Z] 2023-02-15 08:01:47.322877 - Length of input patch is recommended to be a multiple of 32.
[2023-02-15T08:01:50.426Z] num_epochs 2
[2023-02-15T08:01:50.426Z] num_epochs_per_validation 1
[2023-02-15T08:01:50.426Z] [info] training from scratch
[2023-02-15T08:01:50.426Z] [info] amp enabled
[2023-02-15T08:01:50.426Z] ----------
[2023-02-15T08:01:50.426Z] epoch 1/2
[2023-02-15T08:01:50.426Z] learning rate is set to 0.2
[2023-02-15T08:01:50.426Z] monai.transforms.io.dictionary LoadImaged.__init__:image_only: Current default value of argument `image_only=False` has been deprecated since version 1.1. It will be changed to `image_only=True` in version 1.3.
[2023-02-15T08:01:53.697Z] [2023-02-15 08:01:51] 1/4, train_loss: 0.6839
[2023-02-15T08:01:53.697Z] [2023-02-15 08:01:51] 2/4, train_loss: 0.6656
[2023-02-15T08:01:53.697Z] [2023-02-15 08:01:52] 3/4, train_loss: 0.5224
[2023-02-15T08:01:53.697Z] [2023-02-15 08:01:53] 4/4, train_loss: 0.5188
[2023-02-15T08:01:53.697Z] Traceback (most recent call last):
[2023-02-15T08:01:53.697Z]   File "/tmp/tmpp5__p2gw/workdir/dints_0/scripts/train.py", line 479, in <module>
[2023-02-15T08:01:53.697Z]     fire.Fire()
[2023-02-15T08:01:53.697Z]   File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 141, in Fire
[2023-02-15T08:01:53.697Z]     component_trace = _Fire(component, args, parsed_flag_args, context, name)
[2023-02-15T08:01:53.697Z]   File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 475, in _Fire
[2023-02-15T08:01:53.697Z]     component, remaining_args = _CallAndUpdateTrace(
[2023-02-15T08:01:53.697Z]   File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 691, in _CallAndUpdateTrace
[2023-02-15T08:01:53.697Z]     component = fn(*varargs, **kwargs)
[2023-02-15T08:01:53.697Z]   File "/tmp/tmpp5__p2gw/workdir/dints_0/scripts/train.py", line 313, in run
[2023-02-15T08:01:53.697Z]     lr_scheduler.step()
[2023-02-15T08:01:53.697Z]   File "/usr/local/lib/python3.8/dist-packages/torch/optim/lr_scheduler.py", line 149, in step
[2023-02-15T08:01:53.697Z]     values = self.get_lr()
[2023-02-15T08:01:53.697Z]   File "/usr/local/lib/python3.8/dist-packages/torch/optim/lr_scheduler.py", line 749, in get_lr
[2023-02-15T08:01:53.697Z]     decay_factor = ((1.0 - self.last_epoch / self.total_iters) / (1.0 - (self.last_epoch - 1) / self.total_iters)) ** self.power
[2023-02-15T08:01:53.697Z] TypeError: unsupported operand type(s) for ** or pow(): 'float' and 'str'
[2023-02-15T08:01:55.065Z] 
[2023-02-15T08:01:55.065Z] E
[2023-02-15T08:01:55.065Z] ======================================================================
[2023-02-15T08:01:55.065Z] ERROR: test_ensemble (__main__.TestEnsembleBuilder)
[2023-02-15T08:01:55.065Z] ----------------------------------------------------------------------
[2023-02-15T08:01:55.065Z] Traceback (most recent call last):
[2023-02-15T08:01:55.065Z]   File "/home/jenkins/agent/workspace/Monai-notebooks/MONAI/tests/test_auto3dseg_ensemble.py", line 146, in test_ensemble
[2023-02-15T08:01:55.065Z]     algo.train(_train_param)
[2023-02-15T08:01:55.065Z]   File "/tmp/tmpp5__p2gw/workdir/algorithm_templates/dints/scripts/algo.py", line 441, in train
[2023-02-15T08:01:55.065Z]   File "/home/jenkins/agent/workspace/Monai-notebooks/MONAI/monai/apps/auto3dseg/bundle_gen.py", line 191, in _run_cmd
[2023-02-15T08:01:55.065Z]     normal_out = subprocess.run(cmd.split(), env=ps_environ, check=True)
[2023-02-15T08:01:55.065Z]   File "/usr/lib/python3.8/subprocess.py", line 516, in run
[2023-02-15T08:01:55.065Z]     raise CalledProcessError(retcode, process.args,
[2023-02-15T08:01:55.065Z] subprocess.CalledProcessError: Command '['python', '/tmp/tmpp5__p2gw/workdir/dints_0/scripts/train.py', 'run', "--config_file='/tmp/tmpp5__p2gw/workdir/dints_0/configs/transforms_validate.yaml','/tmp/tmpp5__p2gw/workdir/dints_0/configs/transforms_train.yaml','/tmp/tmpp5__p2gw/workdir/dints_0/configs/network.yaml','/tmp/tmpp5__p2gw/workdir/dints_0/configs/hyper_parameters.yaml','/tmp/tmpp5__p2gw/workdir/dints_0/configs/transforms_infer.yaml','/tmp/tmpp5__p2gw/workdir/dints_0/configs/hyper_parameters_search.yaml','/tmp/tmpp5__p2gw/workdir/dints_0/configs/network_search.yaml'", '--training#num_images_per_batch=2', '--training#num_epochs=2', '--training#num_epochs_per_validation=1', '--training#determ=True']' returned non-zero exit status 1.
[2023-02-15T08:01:55.065Z] 
[2023-02-15T08:01:55.065Z] ----------------------------------------------------------------------
[2023-02-15T08:01:55.065Z] Ran 1 test in 91.668s
[2023-02-15T08:01:55.065Z] 
[2023-02-15T08:01:55.065Z] FAILED (errors=1)
```

**Comment by dongyang0122** [comment]
It is fixed in this [PR](https://github.com/Project-MONAI/research-contributions/pull/188).
