### ISSUE TITLE
Auto3DSeg dints search on multi-GPU

### ISSUE THREAD

**Issue by mingxin-zheng** [Project-MONAI/research-contributions#226]
**Describe the bug**
With the command below to run the Auto3DSeg dints algo network search on 2-GPU, I get an error message:

**To Reproduce**
```
torchrun --nnodes=1 --nproc_per_node=2 ./tmp_sim_work_dir/dints_0/scripts/search.py run --config_file='tmp_sim_work_dir/dints_0/configs/transforms_validate.yaml','tmp_sim_work_dir/dints_0/configs/transforms_train.yaml','tmp_sim_work_dir/dints_0/configs/transforms_infer.yaml','tmp_sim_work_dir/dints_0/configs/hyper_parameters_search.yaml','tmp_sim_work_dir/dints_0/configs/network.yaml','tmp_sim_work_dir/dints_0/configs/network_search.yaml','tmp_sim_work_dir/dints_0/configs/hyper_parameters.yaml' --searching#num_epochs_per_validation=1 --searching#num_images_per_batch=2 --searching#num_epochs=2 --searching#num_warmup_epochs=1
```
```
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 1
INFO:torch.distributed.distributed_c10d:Rank 1: Completed store-based barrier for key:store_based_barrier_key:1 with 2 nodes.
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 2 nodes.
2023-04-18 12:47:48.639341 - Length of input patch is recommended to be a multiple of 32.
2023-04-18 12:47:48.653783 - Length of input patch is recommended to be a multiple of 32.
Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
Traceback (most recent call last):
  File "./tmp_sim_work_dir/dints_0/scripts/search.py", line 678, in <module>
    fire.Fire()
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "./tmp_sim_work_dir/dints_0/scripts/search.py", line 399, in run
    probs_a, arch_code_prob_a = dints_space.get_prob_a(child=True)
  File "/workspace/monai/monai-in-dev/monai/networks/nets/dints.py", line 862, in get_prob_a
    probs_a = [
  File "/workspace/monai/monai-in-dev/monai/networks/nets/dints.py", line 864, in <listcomp>
    path_activation * _arch_code_prob_a[blk_idx]
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!
```
**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS
 - Python version
 - MONAI version [e.g. git commit hash]
 - CUDA/cuDNN version
 - GPU models and configuration

**Additional context**

**Comment by mingxin-zheng** [comment]
@dongyang0122

**Comment by pcl1121** [comment]
I met the same problem，have you fixed it?
