### ISSUE TITLE
test.py model_dict = torch.load(pretrained_pth)["state_dict"] gives error

### ISSUE THREAD

**Issue by davidkvcs** [Project-MONAI/research-contributions#67]
**Describe the bug**
When running test.py I am getting the error: 

> Traceback (most recent call last):
>   File "test.py", line 115, in <module>
>     main()
>   File "test.py", line 76, in main
>     model_dict = torch.load(pretrained_pth)["state_dict"]
> KeyError: 'state_dict

**To Reproduce**
1. Go to: 
.../swin-unetr/research-contributions/SwinUNETR/BTCV
2. I installed monai from swin-unetr repo following the [repo readme.](https://github.com/Project-MONAI/research-contributions/tree/main/SwinUNETR/BTCV)
3. Run commands 
```
conda activate <my MONAI swin-unetr environment>
export CUDA_VISIBLE_DEVICES=<my_device_number>
python test.py
```

**Expected behavior**
Test script to run and predict validation cases in my json file without errors. My json file was set up according to your guidlines and works fine for training.

**Environment (please complete the following information):**
 - OS: 

> Operating System: Ubuntu 20.04.4 LTS
> Kernel: Linux 5.13.0-51-generic
> Architecture: x86-64

 - Python version

> python                    3.7.13

 - MONAI version [e.g. git commit hash]

> monai                     0.9.0rc1+31.g38b7943a          pypi_0    pypi

 - CUDA/cuDNN version
 
> pytorch                   1.11.0          py3.7_cuda11.3_cudnn8.2.0_0    pytorch
> cudatoolkit               11.3.1               h2bc3f7f_2

 - GPU models and configuration
NVIDIA A40
NVIDIA-SMI 510.73.05    Driver Version: 510.73.05    CUDA Version: 11.6
or 
NVIDIA A6000
NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4

In doubt exactly what you need for GPU configuration. Not an expert in this. Let me know if you need additional info. 

**Additional context**
During debugging I found out that if I simply change line 76 from 
`model_dict = torch.load(pretrained_pth)["state_dict"]`
to
model_dict = torch.load(pretrained_pth)

The code and prediction seems to run as expected.

Let me know if you need further information.

**Comment by tangy5** [comment]
Hi @davidkvcs , Thanks for reporting this issue. The pre-trained model checkpoints should contain three keys {'epochs': , 'best_acc', 'state_dict': }

Key "state_dict" should be the model weights, could you direct me to the model checkpoints you've tried, I will double check whether the saved model has consistent key-value items. 
Thank you.

**Comment by davidkvcs** [comment]
Hi @tangy5 

I trained the model my self, using this repo. 
Do you have some way I can share this .pth file with you?

Since the next line, `model.load_state_dict(model_dict)` works fine and the prediction look pretty good I assume, the weights are loaded correctly with the changes I made?

It seems my trained model does not have the three keys {'epochs': , 'best_acc', 'state_dict': }, but holds the state_dict only. When I run model_dict = torch.load(pretrained_pth), model_dict is a OrderedDict of length 159, holding what could look like the trained model weights. Examples of field names:

...
swinViT.patch_embed.proj.weight
swinViT.patch_embed.proj.bias
swinViT.layers1.0.blocka.0.norm1.weight
and so on...

Does that make sense?

**Comment by Jamshidhsp** [comment]
@davidkvcs  Hi, could you figure it out. I have the same issue, too.

**Comment by Jamshidhsp** [comment]
@tangy5 Could you please help with finetune issue. When I use the pretrained weights you prepared it works. But when I do the pretraining by myself, and try finetune my model in BTCV, use_pretrained_ssl, I get the error below:
KeyError: 'module.patch_embed.proj.weight'

**Comment by davidkvcs** [comment]
HiI think simply uncommenting the the part [“state_dict”] from the end of line 76 fixed this problem for me. Best David Sent from my iPhoneOn 13 Dec 2022, at 01.11, Jamshidhsp ***@***.***> wrote:﻿
@davidkvcs  Hi, could you figure it out. I have the same issue, too.
